site_name: My Documentation
site_url: https://example.com/docs/

theme:
  name: material # Or 'readthedocs', 'mkdocs', etc.
  palette:
    primary: deep purple
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

nav:
  - Home: index.md
  - Guide:
    - Introduction: guide/introduction.md
    - Setup: guide/setup.md
  - API: api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
